name: metch
description: "A new Flutter project."

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  video_player: 2.1.15
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  metch_ui_kit:
    path: packages/metch_ui_kit

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/logo.png
    - assets/videos/test.mp4
  fonts:
    - family: Tahoma
      fonts:
        - asset: packages/metch_ui_kit/lib/fonts/Tahoma-Regular.ttf
          weight: 400
        - asset: packages/metch_ui_kit/lib/fonts/TAHOMAB0.ttf
          weight: 700

  uses-material-design: true
