name: metch
description: "A new Flutter project."

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter_share: ^2.0.0
  shared_preferences:
  uni_links: ^0.5.1
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  video_player: ^2.4.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  metch_ui_kit:
    path: packages/metch_ui_kit
  http: ^0.13.5
  url_launcher: ^6.0.0
  flutter_linkify: ^3.1.3
  dio: ^4.0.4
  dio_http_cache: ^0.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/logo.png
    - assets/videos/test.mp4
    - assets/images/padel.png
    - assets/images/logoWithShadow.png
    - assets/images/metchTagLine.png
    - assets/images/private_match_bg.png
    - assets/images/Aghead.png
    - assets/images/Devid.png
    - assets/images/Hani.png
    - assets/images/Michael.png
  fonts:
    - family: Tahoma
      fonts:
        - asset: packages/metch_ui_kit/lib/fonts/Tahoma-Regular.ttf
          weight: 400
        - asset: packages/metch_ui_kit/lib/fonts/TAHOMAB0.ttf
          weight: 700

  uses-material-design: true
