name: metch_ui_kit
description: This package contains UI related components for Metch (styles, buttons etc)
version: 0.0.1

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  http: ^0.13.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true